language: perl
perl:
    - "5.24"
    - "5.22"
    - "5.20"
    - "5.18"
    - "5.16"
    - "5.14"
before_install:
    - "cpanm Dist::Zilla"
    - "cpanm Test::More"
    - "cpanm Devel::Cover::Report::Coveralls"
    - "cpanm Devel::Cover::Report::Codecov"
install:
     - export RELEASE_TESTING=1 AUTOMATED_TESTING=1 AUTHOR_TESTING=1 HARNESS_OPTIONS=c HARNESS_TIMER=1
     - cpanm --quiet --notest Devel::Cover::Report::Coveralls
     - cpanm --quiet --notest --installdeps .
script:
     - PERL5OPT=-MDevel::Cover=-coverage,statement,branch,condition,path,subroutine prove -lrsv t
     - cover

after_success:
    - cover -report coveralls
    - cover -report codecov
